### ISSUE TITLE
Unreleased CGImageRef caused memory leak

### ISSUE THREAD

**Issue by tc1993** [ShawnFoo/FXAnimationEngine#1]
The copyImageRef created from CGBitmapContextCreateImage didn't call release method. 

One way to fix this leak is letting RAC to control the retainCycle of the copyImageRef by using __bridge_transfer.

**Comment by ShawnFoo** [comment]
Thanks!
Fixed this bug by returning a decoded UIImage creating by the copyImageRef inside UIImage+FXDecoder.h implement. 

Whoever calling the fx_decodedImage method from UIImage+FXDecoder category won't care about the ownership of the decoded image.
